name: Deploy Strapi to ECS

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: us-east-1
  ECR_REPO: strapi-deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Verify AWS Credentials
      run: aws sts get-caller-identity

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 209378969061.dkr.ecr.$AWS_REGION.amazonaws.com

    - name: Build Docker image
      run: |
        docker build -t $ECR_REPO .

    - name: Tag and Push Docker image
      run: |
        docker tag $ECR_REPO:latest 209378969061.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:latest
        docker push 209378969061.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:latest

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      working-directory: ./my-ecs-deployment
      run: terraform init

    - name: Terraform Apply
      working-directory: ./my-ecs-deployment
      run: terraform apply -auto-approve
